
// Purpose: To store the route constants for the application.
export const ROUTE_CONSTANTS = {
  BASE_PATH: '/trip-expense-manager',
  FETCH: '/fetch',
  HOME: '/',
  NOT_FOUND: '/405',
  Home_PAGE : '/HomePage',
  FAV_ICON:"/favicon.ico",
  DASHBOARD: "/dashboard",
  TRIPS: "/trips",
  EXPENSES: "/expenses",
  ADDTRIP: "/addtrip",
  REPORT: "/report",
  ADDORUPLOADREPORT: "/add-or-upload-report",
  TRIPDETAILS: "/tripdetails",
  USERS: "/settings/users",
  USERDETAILS: "/settings/userdetails",
  ADDUSER: "/settings/adduser",
  BUDGETS: "/budgets",
  ADDBUDGET: "/addbudget",
  BUDGETDETAILS: "/budgetdetails",
  SETTINGS: "/settings",
  DEPARTMENTS: "/settings/departments",
  DEPARTMENTDETAILS: "/settings/departmentdetails",
  ROLESANDPERMISSIONS: "/settings/roles-and-permissions",
  ORGANIZATIONPROFILE: "/settings/organization-profile",
  CURRENCIES: "/settings/currencies",
  TAXES: "/settings/taxes",
  TAGS: "/settings/tags",
  SUBSCRIPTION: "/settings/subscription",
  REPORTAUTOMATION: "/settings/report-automation",
  WORKFLOWRULES: "/settings/workflow-rules",
  ACTIONS: "/settings/actions",
  SCHEDULES: "/settings/schedules",
  ROLESANDPERMISSIONFORM: "/settings/rolesandpermissionform",
  ROLESINFO:"/settings/rolesandpermissions/rolesinfo",
};